import {
  Bookmark,
  Camera,
  Facebook,
  Fingerprint,
  Heart,
  Instagram,
  LightbulbIcon,
  Menu,
  Share2,
  Sparkles,
  Twitter,
  Upload,
  Users,
  X,
  Zap,
} from "lucide-react";

export const ICONS = {
  CAMERA: Camera,
  SPARKELS: Sparkles,
  THUNDER: Zap,
  UPLOAD: Upload,
  LIGHTBULB: LightbulbIcon,
  MENU: Menu,
  CROSS: X,
  SAVE: Bookmark,
  SHARE: Share2,
  LIKE: Heart,
  INSTAGRAM: Instagram,
  FACEBOOK: Facebook,
  TWITTER: Twitter,
  USERS: Users,
  FINGERPRINT: Fingerprint,
};
