export const themes = [
  { id: "love", name: "Love", icon: "❤️" },
  { id: "sad", name: "Sad", icon: "😢" },
  { id: "melancholy", name: "Melancholy", icon: "😭" },
  { id: "happy", name: "Happy", icon: "🎉" },
  { id: "tragic", name: "Tragic", icon: "🥀" },
  { id: "sciFi", name: "Sci-Fi", icon: "👽" },
  { id: "thriller", name: "Thriller", icon: "🔪" },
  { id: "adventure", name: "Adventure", icon: "🧗" },
  { id: "comedy", name: "Comedy", icon: "😂" },
  { id: "horror", name: "Horror", icon: "👻" },
  { id: "crime", name: "Crime", icon: "🕵️" },
  { id: "mystery", name: "Mystery", icon: "🧩" },
  { id: "drama", name: "Drama", icon: "🎭" },
  { id: "romance", name: "Romance", icon: "💘" },
  { id: "animation", name: "Animation", icon: "🎨" },
];
